### ISSUE TITLE
TESTSSSSS

### ISSUE THREAD

**Issue by blesh** [Netflix/ember-nf-graph#1]
This library was developed in a hurry and is definitely battle-tested, but it's *woefully* under-tested.

All major components need more unit tests around them. And Travis needs to be set up. This is a requirement to get out of beta.

**Comment by blesh** [comment]
The big hold up here is a solid way to do integration testing in Ember. I've been pointed at a few techniques by @jamesarosen and @ef4, but I've been unable to get them working.

This is a desperate need for the stability of this library, but I feel I'll have to punt until Ember's documentation catches up with reality.

**Comment by ef4** [comment]
https://github.com/Netflix/ember-nf-graph/pull/91
