### ISSUE TITLE
Bar chart xScaleType="ordinal" hides x-axis labels

### ISSUE THREAD

**Issue by blangslet** [Netflix/ember-nf-graph#101]
Adding xScaleType="ordinal" to get a properly formatted bar chart hides the x-axis labels.

![screen shot 2015-08-25 at 1 15 51 pm](https://cloud.githubusercontent.com/assets/1318543/9478281/ab1bfb12-4b2b-11e5-9ff7-d3a03957683a.png)

Removing xScaleType="ordinal" shows labels but formatting is jacked.

![screen shot 2015-08-25 at 1 14 49 pm](https://cloud.githubusercontent.com/assets/1318543/9478299/c3435aa0-4b2b-11e5-95cb-00dbd3ed5012.png)

I'm assuming it has something to do with the way ticks are calculated in the nf-x-axis component. Going to look into it more in depth tomorrow. 

For reference, this is the template code I'm using:

```javascript
     {{#nf-graph
        xScaleType="ordinal"
        yMinMode="fixed"
        yMin=0
        width=336
        height=206
        showFrets=false
        showLanes=true
        paddingTop=10
        paddingLeft=-18
        paddingRight=0}}

        {{#nf-x-axis tickCount=7 as |tick|}}
          <text>{{tick.value}}</text>
        {{/nf-x-axis}}

        {{#nf-y-axis as |tick|}}
          <text>{{tick.value}}</text>
        {{/nf-y-axis}}

        {{#nf-graph-content}}

          {{nf-bars
            data=averageVisitorsPerDayOfWeek
            barWidth=18
            barClass="barz"}}

        {{/nf-graph-content}}
      {{/nf-graph}}
```

**Comment by blesh** [comment]
It's probably some oversight in the logic that generates the ticks. Thanks for pointing that out.

**Comment by blangslet** [comment]
I didn't have time to dig in too deep, but I hacked together a quick solution:

At: https://github.com/Netflix/ember-nf-graph/blob/master/app/components/nf-x-axis.js#L240

```javascript
uniqueXData: Ember.computed.uniq('graph.xData'),
```
I couldn't find xData in nf-graph, so changed it to xDomain and got the x-axis values passed down.

```javascript
uniqueXData: Ember.computed.uniq('graph.xDomain'),
```
The labels were a little askew so at https://github.com/Netflix/ember-nf-graph/blob/master/app/components/nf-x-axis.js#L269 
```javascript
var halfBandWidth = (xScaleType === 'ordinal') ? xScale.rangeBand() / 2 : 0;
```
I divided by 4 and labels centered nicely.
```javascript
var halfBandWidth = (xScaleType === 'ordinal') ? xScale.rangeBand() / 4 : 0;
```

![screen shot 2015-08-26 at 2 27 00 pm](https://cloud.githubusercontent.com/assets/1318543/9507224/7d216626-4c01-11e5-92bd-84fb78d65dc2.png)


And I didn't find this documented, but in order to do a correct moment transform on the labels, I used useTemplate=true to expose the template markup in the component block.

```javascript
{{#nf-x-axis useTemplate=true tickCount=7 as |tick|}}
  <text>{{moment-format tick.value 'E' 'ddd'}}</text>
{{/nf-x-axis}}
```
![screen shot 2015-08-26 at 2 56 16 pm](https://cloud.githubusercontent.com/assets/1318543/9507418/05a865b6-4c03-11e5-8600-52aa0748e139.png)

**Comment by blesh** [comment]
Thanks @blangslet! ... I'm sorry I don't have time to get to this... do you think you could submit a PR?

**Comment by blangslet** [comment]
On a deadline right now, but hopefully will have some time this weekend!

**Comment by blesh** [comment]
Whatever works. I appreciate all the help I can get. ;)

**Comment by koryteg** [comment]
changing the ticks doesn't seem to work for me as well, 
``` handlebars
{{#nf-x-axis tickCount=5 as |tick|}}
    {{debugger}}
    <text>x is {{tick.value}}</text>  
{{/nf-x-axis}}
``` 

the `x is` doesnt show up, and the `debugger` isn't executing. im on `ember 1.13.8`. dont have time to look at it now but maybe this weekend or monday.
