### ISSUE TITLE
Axes don't recompute if data object is modified

### ISSUE THREAD

**Issue by jamesarosen** [Netflix/ember-nf-graph#108]
If I *modify* rather than *replace* the `data` array, the axes don't recompute.

My code looks something like

```js
data: computed(function() { return Ember.A(...); },

start: function() { this._poll(); },

_poll: function() {
  const data = this.get('data');
  data.pushObject(...);
  data.shiftObject();
  Ember.run.later(this, '_poll', 1000);
};
```

Changing
```js
dataExtents: computed('graphics.@each.data', function(){
```
to
```js
dataExtents: computed('graphics.@each.mappedData.[]', function(){
```
fixes the problem.

**Comment by blesh** [comment]
That seems legit. We're probably always setting data (even with the same array over and over) in our apps given how our data arrives.

@jamesarosen, either @jayphelps or I are going to try to merge some of these PRs today. We have some bug fixes for the area components we need to get in.
