### ISSUE TITLE
Rename project to ember-nf-graph

### ISSUE THREAD

**Issue by jayphelps** [Netflix/ember-nf-graph#11]
<:bike:>

Since ember-cli is now [the "official" way to use ember](http://guides.emberjs.com/v1.11.0/ember-cli/), many in the community (including myself) think new projects should stop including "cli" in their name since it's implied/redundant. I vote a name change to simply `ember-nf-graph` before this gains any major traction.

</:bike:>

Cc/ @blesh

**Comment by blesh** [comment]
you really need a shed emoji.

I named it as such because back when this was born as maybe the second-ever Ember-CLI add-on, @ebryn and @stefanpenner told me to name things prefixed with `ember-cli-`.

I think I'll leave this one how it is for now, unless the community screams out otherwise.

**Comment by jayphelps** [comment]
@blesh I'll be over to your cube in 5.

![me](https://38.media.tumblr.com/a9022cb3d0b74279c8f7ebf3b4e0bfbc/tumblr_mp9aukHSSo1r6dsjro1_500.gif)

**Comment by blesh** [comment]
LOL

**Comment by blesh** [comment]
Okay, so this will happen soon

**Comment by jayphelps** [comment]
![fuck yeah](http://media2.giphy.com/media/hsBZfDG7wiWHu/giphy.gif)

**Comment by blesh** [comment]
Done.
