### ISSUE TITLE
Ember 2.0 support

### ISSUE THREAD

**Issue by benlesh** [Netflix/ember-nf-graph#110]
Currently, my team doesn't have the bandwidth to upgrade our apps from Ember 1.12 to Ember 2.0, and consequently, Ember 2.0 support for this add-on is _not_ a priority for us at this time.

However, I'm sympathetic , and I've started a [jj-abrams branch](https://github.com/netflix/ember-nf-graph/tree/jj-abrams) for those of you that would like to try your hand to adding support for Ember 2.0.

Any and all PRs around this issue are welcome, and we're happy to help in any way we can.

**Comment by zkwentz** [comment]
We're using this extensiviely in Origin Story, would love to help out where I can @blesh.

**Comment by acorncom** [comment]
Looks like this issue can be closed
