### ISSUE TITLE
nf-x-axis documentation

### ISSUE THREAD

**Issue by zkwentz** [Netflix/ember-nf-graph#111]
Hey all,

`nf-x-axis` documentation doesn't show in the example that you need to specify `useTemplate=true` or it won't yield to your block. Doesn't look like the option is in the docs either, http://netflix.github.io/ember-nf-graph/docs/classes/components.nf-x-axis.html.

Putting this here for others, until I can open a PR this evening to update docs.

**Comment by zkwentz** [comment]
Okay, now looking at the code, I'm seeing it's not a documentation issue, the logic is to check if a block has been passed, and if it is, `useTemplate` is false, if it isn't `useTemplate` is true. 

Going to run through this and see what version of ember / handlebars / emblem I'm running and if they have an issue with `hasBlock`.

**Comment by zkwentz** [comment]
Looks like it was due to `hasBlock` not being available from within the component, only in the template. I modified the logic a bit to always use `hasBlock` and set a property if we're pre-glimmer (`template` is available).

**Comment by SirZach** [comment]
Doesn't look like your changes made it out. I'm using <code>1.0.0-beta.31</code> and still had to set <code>useTemplate</code> to true. Also, even on the latest master version, the y-axis still references <code>useTemplate</code> instead of <code>hasBlock</code>. Thanks!

**Comment by blesh** [comment]
@SirZach looks like I need to publish a new version still.
