### ISSUE TITLE
Changing selected doesn't change CSS selected class

### ISSUE THREAD

**Issue by jeff3dx** [Netflix/ember-nf-graph#16]
With multiple nf-lines on a graph click a line to select it.  The nf-graph "selected" property object reference changes correctly but the "selected" CSS class is not applied to the new selection.

**Comment by blesh** [comment]
Seems like something caused by the update to 1.10

**Comment by blesh** [comment]
This seems to be a problem with Ember itself. I'll file a bug.

**Comment by jayphelps** [comment]
Reopening until upstream bug is fixed.

**Comment by blesh** [comment]
I patched it in ember-nf-graph... I'm submitting a PR for ember, tho.

**Comment by jayphelps** [comment]
@blesh ah okay. If this isn't impacting nf-graph, feel free to reclose

**Comment by blesh** [comment]
It's not impacting nf-graph at the moment.
