### ISSUE TITLE
Use ember-cli-sass instead of pre-compiling scss

### ISSUE THREAD

**Issue by jayphelps** [Netflix/ember-nf-graph#18]
> To work around an issue with including SASS in an Ember-CLI Add-On, the styles and building thereof, are now located under styles/ and must be built from the command line as so:

[README.md#generating-styles](https://github.com/Netflix/ember-cli-nf-graph/blob/3c97c32bc02ab382713caaf2260f048fba2e5c41/README.md#generating-styles)

Basically, this isn't needed anymore.

**Comment by blesh** [comment]
Right. The style thing was a remnant of this being an old ember cli ~0.0.38 project.

**Comment by blesh** [comment]
Closing this completely as I'm moving away from SASS entirely. I find it encourages overly specific CSS output. See #96
