### ISSUE TITLE
Docs links broken

### ISSUE THREAD

**Issue by ksnyde** [Netflix/ember-nf-graph#33]
The documentation links from the README appear to be broken (404 error). 

![2015-04-17_08-49-59](https://cloud.githubusercontent.com/assets/980757/7197921/bcbd96fe-e4de-11e4-8aea-2a61cbcc8116.png)

**Comment by blesh** [comment]
That's strange. It appears renaming the repository as broken GitHub pages functionality. the `gh-pages` branch is there, with the appropriate files... Hmmm...

**Comment by blesh** [comment]
Apparently, I just need to push them again. Thanks so much, @ksnyde, for pointing this out.
