### ISSUE TITLE
[Bug] D3.js not found

### ISSUE THREAD

**Issue by truenorth** [Netflix/ember-nf-graph#36]
#### Steps to reproduce

`ember new nfgraph-test; cd nfgraph-test`
`ember install ember-nf-graph`
`ember s`

![screen shot 2015-04-17 at 3 36 10 pm](https://cloud.githubusercontent.com/assets/558005/7212115/8349cfee-e517-11e4-9a80-401c8dea4d08.png)

**package.json**
```js
 "ember-nf-graph": "1.0.0-beta.8",
```

**Comment by blesh** [comment]
This is apparently already fixed. The issue was that the blueprint folder was still named `ember-cli-nf-graph`. 

Running `ember-cli-nf-graph` will solve this issue for now, this will not be present in the next release (later today).

**Comment by truenorth** [comment]
![200-1 copy](https://cloud.githubusercontent.com/assets/558005/7262634/12316896-e830-11e4-9a93-7c1fa995f33d.gif)
