### ISSUE TITLE
Examples are missing in FF 28

### ISSUE THREAD

**Issue by technomage** [Netflix/ember-nf-graph#47]
When the examples page is viewed in FF 28 on mac all the graphs are blank.  Safari and Chrome both show this content.

**Comment by technomage** [comment]
Note in FF 37.0.1 the following errors appear:

Unexpected value NaN parsing x1 attribute. vendor.js:13215:0
Unexpected value NaN parsing x2 attribute. vendor.js:13215:0
Unexpected value NaN parsing y1 attribute. vendor.js:13215:0
Unexpected value NaN parsing y2 attribute. vendor.js:13215:0

**Comment by blesh** [comment]
Attn @jeff3dx ... This probably just needs updated to the latest version.

I'm unsure about why they're not showing up in older versions of FF. These components were developed to target newer Chrome and FF browsers used by engineers at Netflix. I probably don't have time or justification to look into that, but I'm happy to take PRs on the matter, or suggestions.

**Comment by blesh** [comment]
If time allows, I will of course look into this. I just can't justify prioritizing it, if that makes sense.

**Comment by blesh** [comment]
@technomage the examples were updated. I haven't yet looked at them in FF 28. Can you see if they're fine now?

**Comment by blesh** [comment]
Since there was no response and I have been unable to duplicate the issue, closing this issue.
