### ISSUE TITLE
Remove RxJS as a dependency

### ISSUE THREAD

**Issue by jayphelps** [Netflix/ember-nf-graph#50]
Needing to pull in RxJS via RxEmber (or ember-cli-rx) seems very unnecessary and boatful. The current places it's used seem very easy to do without Rx and would save consumers significant file size.

**Comment by blesh** [comment]
> Needing to pull in RxJS via RxEmber (or ember-cli-rx) seems very unnecessary and boatful. 

![Boatful](http://images5.fanpop.com/image/photos/30400000/Love-Boat-the-love-boat-30440820-1200-803.jpg)

**Comment by jayphelps** [comment]
Hahahahahahahahahahahahahah im dying help call 911 hahahahahahaa

**Comment by SirZach** [comment]
freshly installing this addon also did not include Rx. I needed to do a <code>npm install --save-dev ember-cli-rx</code> and an <code>bower install --save-dev rxjs</code> for it to work.

**Comment by jayphelps** [comment]
Yep, it's not [here](https://github.com/Netflix/ember-nf-graph/blob/master/blueprints/ember-nf-graph/index.js) but it needs to be.

**Comment by blesh** [comment]
This should be cleared up now. (The meta issue of rxjs not installing properly)

**Comment by jayphelps** [comment]
Technically it's not :p this was to remove RxJS as a dependency entirely of nf-graph since it's a rather large lib for what we're using it for. As discussed, it's OK to punt on this for now, until outside contributors care enough. But I'd prefer this ticket left open since it is indeed not ideal. I'll let it be your call, but that's IMO.

**Comment by blesh** [comment]
Meh. Okay.

**Comment by jayphelps** [comment]
<3

**Comment by blesh** [comment]
I'm closing this as it's not a priority for us, or seemingly anyone else at the moment. I'm happy to take PRs around it, of course.
