### ISSUE TITLE
Stop registering children during willInsertElement

### ISSUE THREAD

**Issue by blesh** [Netflix/ember-nf-graph#53]
Per a discussion with @stefanpenner, this is causing re-render of components and slowness. In particular, axes are problematic.

**Comment by stefanpenner** [comment]
One thing worth noting, it isn't that all registrations are inherently going to cause performance issues. I did notice that some of them in nf-graph. where themselves causing data changes that would require further render updates.

Doing this these extra renders obviously means we need to render parts twice. This clearly should be avoided. The caveat is, it isn't clear that this is actually happening.

**Comment by blesh** [comment]
@stefanpenner one quirky thing I'm doing that was a sort of "hack" recommended by @ebryn is seen in the nf-graph component. This is where i have a `willInsertElement` that is setting a `hasRendered` to `true`. That `hasRendered` is used in an `{{#if}}` in the template that tells it it's okay to render. This was because I needed a way to delay the render until the children were ready. I'll have to experiment with other ways to do this, as it will not be straightforward. It's also possible that I no longer need to do this, and it's legacy code. I'm unsure.

**Comment by blesh** [comment]
PR #54 is related.

Interestingly, when I run benchpress against this PR branch and the code *before* the PR, the code before the PR is some trivial amount faster, on average, 10 ms or so.
