### ISSUE TITLE
autoscaling width

### ISSUE THREAD

**Issue by SirZach** [Netflix/ember-nf-graph#57]
If I set <code>{{#nf-graph width="100%"}}</code> this works okay but when trying to combine that with an <code>{{nf-bars}}</code> things go awry and the bars end up stacked on top of each other.

**Comment by blesh** [comment]
nf-graph doesn't support percentage based widths for a variety of reasons discussed here #49 

We may in the future support this, but it's not likely to work well in some browsers, and could be computationally expensive, depending on how it's implemented.
