### ISSUE TITLE
Bars displaying only in one column but tracked x and y values actually move

### ISSUE THREAD

**Issue by JacoSmit** [Netflix/ember-nf-graph#59]
Hi, I have the following input data for a bars graph but for some reason the bars only display in one column: 

```
menuItemStockCount: [
    { x: 0, y: 200 },
    { x: 1, y: 154 },
    { x: 2, y: 130 },
    { x: 3, y: 300 }
  ]
```
My code in my .hbs file to display the graph is:
```
{{#nf-graph width=500 
		   height=300 
		   paddingRight=10 
		   paddingTop=10 
			xScaleType="ordinal" 
			yMinMode="fixed" 
			yMin=0
			showLanes=true
    		showFrets=true
    		}}
  {{#nf-graph-content}}
    
    {{nf-bars data=model.menuItemStockCount
				trackingMode="snap-last"
		trackedData=tracked}}    
    
  {{/nf-graph-content}}

  {{#nf-y-axis as |tick|}}
    <text>{{tick.value}}</text>
  {{/nf-y-axis}}

  {{#nf-x-axis as |tick|}}
    <text>{{tick.value}}</text>
  {{/nf-x-axis}}

 {{/nf-graph}}

 <text>{{tracked.x}} {{tracked.y}}</text>
```

Am I just doing something wrong?

**Comment by blesh** [comment]
What version of nf-graph are you on? Latest?

**Comment by JacoSmit** [comment]
Hi yes I am on the lastest version of nf-graphs. An image of the current graph is:
![screenshot from 2015-05-14 19 58 10](https://cloud.githubusercontent.com/assets/11595650/7658444/993de4f0-fb3a-11e4-9ddd-284666b7aa53.png)

**Comment by blesh** [comment]
Okay, thanks, I'll take a look. Strange that we're not seeing this issue yet...
