### ISSUE TITLE
wrong property names for x and y

### ISSUE THREAD

**Issue by jesse-black** [Netflix/ember-nf-graph#60]
The documentation for [nf-line](https://netflix.github.io/ember-nf-graph/docs/classes/components.nf-line.html) (and others) says the `x` and `y` properties contains the paths to access on each data object. But doing 

    {{nf-line data=model x="foo" y="bar"}}

didn't work. It seems the properties are actually named `xprop` and `yprop`, and doing

    {{nf-line data=model xprop="foo" yprop="bar"}}

instead worked for me.

**Comment by blesh** [comment]
Thanks for letting us know.
