### ISSUE TITLE
Tick labels don't work on Glimmer

### ISSUE THREAD

**Issue by jamesarosen** [Netflix/ember-nf-graph#70]
On ember 1.13.2, when I do
```hbs
{{#nf-y-axis as |tick|}}
  <text>{{tick.value}}%</text>
{{/nf-y-axis}}
```
I get the tick lines, but no labels.

Additionally, the guides don't show the `tick` block-param , though the code seems to expect that.

**Comment by blesh** [comment]
Yeah, this because there is no longer an idiomatic way to share templates in Ember 1.13. (as I responded to you in Slack). There isn't much that can be done to fix this properly for now. 

Might be able to do some hacky workarounds... like giving an optional component name to the axis component that loads the component and gives it the tick value. I'm still unsure how I'd give it the proper scope to share actions though.

**Comment by jamesarosen** [comment]
I have this working (for my use-case; I'm not sure if there's another important case I'm missing) with
```hbs
<line x1="0" {{bind-attr y1=axisLineY x2=width y2=axisLineY }}></line>

{{#each ticks as |tick|}}
  <g class="tick">
    {{#view 'nf-tick-label' controller=graph.parentController x=tick.x y=tick.labely}}
      {{#if hasBlock}}
        {{yield tick}}
      {{else}}
        <text>{{tick.value}}</text>
      {{/if}}
    {{/view}}

    <line {{bind-attr x1=tick.x y1=tick.y1 x2=tick.x y2=tick.y2}}></line>
  </g>
{{/each}}
```

**Comment by jamesarosen** [comment]
I also don't know what "share templates" means. My only guess is that you want to have one block that gets used for both the x- and y-axis, it I don't know what that would like like.

**Comment by blesh** [comment]
> 

It was my understanding, from a conversation with Mike North, that [this no longer works in 1.13](https://github.com/Netflix/ember-nf-graph/blob/ff682a7fc857ac7cf827ea26ed77ed5a766c13f2/app/templates/components/nf-x-axis.hbs#L14)

**Comment by jamesarosen** [comment]
I guess what I'm saying is that I don't understand that line you linked to. In the template I posted above, there are two cases:

 1. the user called it with a block: `{{#nf-x-axis as |tick|}}<text>{{tick.value}}</text>{{/nf-x-axis}}`
 2. the user called it without a block: `{{nf-x-axis}}`

But in your template, there are three:

 1. `template.blockParams` is true and `useDefaultTemplate` is true
 2. `template.blockParams` is true but `useDefaultTemplate` is false
 3. `template.blockParams` is false

But I don't know how those three map to usage.

If you could show me examples of those three cases, I might be able to emulate them in the new world. (Or we might be able to eliminate a case that's no longer relevant!)

**Comment by blesh** [comment]
So the useDefaultTemplate thing was snuck past me, I think. I don't recall adding that. it's an interesting feature, but it shouldn't depend on block params.

1. `{{#nf-x-axis useDefaultTemplate=true as |tick|}}{{/nf-x-axis}}`
2. `{{#nf-x-axis as |foo|}}<text>{{foo.value}}</text>{{/nf-x-axis}}` 
3. `{{#nf-x-axis}}<text>{{tick.value}}{{/nf-x-axis}}

#2 is the most common case.  #3 is deprecated.  #1 should probably be changed to not require the block params.

**Comment by jamesarosen** [comment]
What's the default template? Couldn't we just use that when `hasBlock` is false? If you want *no* content, you could always do `{{#nf-x-axis}}{{/nf-x-axis}}`. Then we can eliminate `useDefaultTemplate`, which lets us move to Glimmer!

**Comment by jamesarosen** [comment]
Since the default template is `<text>{{tick.value}}</text>`, my implementation above supports (1) and (2). (3) isn't proper ember style and I think you're right to deprecate it. Getting rid of the `bind-attr`s and converting `nf-tick-label` to an `Ember.Component` leaves us with

```hbs
<line x1="0" y1="{{axisLineY}}" x2="{{width}}" y2="{{axisLineY}}"></line>

{{#each ticks as |tick|}}
  <g class="tick">
    {{#nf-tick-label controller=graph.parentController x=tick.x y=tick.labely}}
      {{#if hasBlock}}
        {{yield tick}}
      {{else}}
        <text>{{tick.value}}</text>
      {{/if}}
    {{/nf-tick-label}}

    <line x1="{{tick.x}}" y1="{{tick.y1}}" x2="{{tick.x}}" y2="{{tick.y1}}"></line>
  </g>
{{/each}}
```

**Comment by blesh** [comment]
Looks great! 3 has been giving deprecation warnings for some time now, and I'm okay with breaking that considering the low number of consumers of this library and the fact that we're still in beta.

**Comment by jamesarosen** [comment]
64e657cb doesn't work because `hasBlock` isn't a property on the component. It's an Ember-Handlebars "special" key. See https://github.com/emberjs/ember.js/blob/eeb8ee905171483e47ace7786ffcf7e62d8ea985/packages/ember-htmlbars/lib/hooks/get-root.js#L9
