### ISSUE TITLE
Mouse Tracking doesn't work on Glimmer

### ISSUE THREAD

**Issue by jamesarosen** [Netflix/ember-nf-graph#71]
On Ember 1.13.2 and latest Chrome, I have the following:

```hbs
{{#nf-graph selected=selectedLine}}
  {{#nf-graph-content}}
    {{nf-vertical-line x=selectedLine.hoverData.x}}
    {{nf-horizontal-line y=selectedLine.hoverData.y}}

    {{nf-line data=data trackingMode="hover" selectable=true selected=true}}
   {{/nf-graph-content}}
{{/nf-graph}}
```

I've logged the `hoverData` objects; they all come up with `x: null, y: null`.

**Comment by blesh** [comment]
We're still working in 1.11, so it's going to be a while before I can reasonably address this.

**Comment by blesh** [comment]
I'm interested to see if this works in #86 since I've completely refactored the tracking dot logic. I'm still in 1.11 on all of my projects, and we still don't have a means of creating integration tests I can run in Glimmer. @jamesarosen can you check once #86 is merged?

**Comment by blesh** [comment]
This needs to be tested against `1.0.0-beta.22` and Ember 2.0 ... I don't have the bandwidth at the moment.

**Comment by blesh** [comment]
ping @jamesarosen have you had a chance to check the latest version?

**Comment by jamesarosen** [comment]
I haven't. I'll try to give it a shot this week or weekend.

**Comment by blesh** [comment]
Thanks @jamesarosen
