### ISSUE TITLE
How can I label every line or area chart inside a graph-content?

### ISSUE THREAD

**Issue by juliankmazo** [Netflix/ember-nf-graph#75]
Hi. I can't find, or I don't understand how can I label every chart inside a graph-component. I would like to put labels and colors so I can easily differentiate every line in one chart.

Can someone help me please :)

**Comment by blesh** [comment]
@juliankmazo you can do anything you'd normally do with SVG or HTML, really. It just depends where you want your legend to live, or what you want your design to look like.

The colors of the `nf-line` components and others can be set via the `class` attribute on the component. You'd create a class and set the `stroke` color of the line with CSS.
