### ISSUE TITLE
Brush Select To Zoom throws "Cannot read property 'insertBefore' of null"

### ISSUE THREAD

**Issue by blangslet** [Netflix/ember-nf-graph#85]
Any click and drag event on the "Brush Select to Zoom" graph throws "Uncaught TypeError: Cannot read property 'insertBefore' of null."

![screen shot 2015-07-20 at 2 03 09 pm](https://cloud.githubusercontent.com/assets/1318543/8787344/73eeff4a-2ee8-11e5-98b1-d176c64b4a8b.png)

**Comment by blesh** [comment]
Thanks. Is this in the examples page?

**Comment by blangslet** [comment]
Yep! http://netflix.github.io/ember-nf-graph-examples/dist/#brush-select-zoom . Playing with it throws the console error.

**Comment by blesh** [comment]
@blangslet it looks like an issue where the examples need to be updated to the latest version of the graph components and Ember 1.12. It's doing something strange where it's looking for a parentElement on a detached comment node. I'm not sure what that's about. Either way, Ember is behind and so are the components on the Example page.

**Comment by blangslet** [comment]
@blesh I'm running ember 1.12.0 and ember-nf-graph 1.0.0-beta.20 and still seem to be getting the error. Were you able to clear it out?

Awesome library by the way, comparing charting options right now for a reporting/dataviz dashboard and it seems like this is the way to go. Awesome work!

**Comment by blesh** [comment]
I appreciate the complement. I'm a little concerned about this bug because we haven't run into it here. At least it's in the example app so I can debug it. We desperately need to get the newer integration tests working on this repo.

**Comment by blesh** [comment]
Fixed this issue, it turns out that since I was manually updating the DOM, Ember was disagreeing with me.

**Comment by blesh** [comment]
fixed in 1.0.0-beta.22

**Comment by blangslet** [comment]
Woohoo, thanks Ben!!
